name: Run Twitter Bot

on:
  schedule:
    - cron: "*/20 * * * *"  # Runs every 20 minutes
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-bot:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./agent

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up environment variables
        run: |
          echo "CONTRACT_ID=${{ secrets.CONTRACT_ID }}" >> $GITHUB_ENV
          echo "ORACLE_ACCOUNT_ID=${{ secrets.ORACLE_ACCOUNT_ID }}" >> $GITHUB_ENV
          echo "ORACLE_PRIVATE_KEY=${{ secrets.ORACLE_PRIVATE_KEY }}" >> $GITHUB_ENV
          echo "TWITTER_BEARER_TOKEN=${{ secrets.TWITTER_BEARER_TOKEN }}" >> $GITHUB_ENV
          echo "TWITTER_API_KEY=${{ secrets.TWITTER_API_KEY }}" >> $GITHUB_ENV
          echo "TWITTER_API_SECRET=${{ secrets.TWITTER_API_SECRET }}" >> $GITHUB_ENV
          echo "TWITTER_ACCESS_TOKEN=${{ secrets.TWITTER_ACCESS_TOKEN }}" >> $GITHUB_ENV
          echo "TWITTER_ACCESS_SECRET=${{ secrets.TWITTER_ACCESS_SECRET }}" >> $GITHUB_ENV
          echo "TWITTER_USER_ID=${{ secrets.TWITTER_USER_ID }}" >> $GITHUB_ENV
          echo "WEB_APP_BASE_URL=${{ secrets.WEB_APP_BASE_URL }}" >> $GITHUB_ENV

      - name: Run Twitter Bot
        run: python bot.py
